(eval-after-load 'clojure-mode
  '(my/extra-clojure-indent))

(defun my/extra-clojure-indent ()
  (define-clojure-indent
    (doto-let 1)
    (assert-args 1)
    (case-expr 1)
    (<- 1)
    (c/?<- 2)
    (domonad 1)
    (m/domonad 1)
    (fact?- 1)
    (before 1)
    (after 1)
    (ignore-errors 0)
    (returning 1)
    (cli 1)
    (do-line-bytes 1)
    (around 1)
    (background 0)
    (run* 1)
    (l/run* 1)
    (run 2)
    (l/run 2)
    (fresh 1)
    (tabled 1)
    (http/post 1)
    (http/get 1)
    (lc/create-default 1)
    (recuring 1)
    (compile-if 1)
    (table-descriptor 1)
    (column-descriptor 1)
    (GET 1)
    (POST 1)
    (PUT 1)
    (DELETE 1)))

(provide 'llasram-clojure-indent)
