#! /bin/bash

echo -n \
    $(mpc -f '%position%. %title%' current) \
    '|' $(uptime | sed 's/.*://; s/,//g') \
    '|' $(acpi -b 2>&1 | grep -Eo '[0-9]+%' | paste -d' ' -s) \
    '|' $(env TZ=America/New_York date)
