#! /bin/bash

# This file is sourced by bash when you log in interactively.

# Load general bash configuration
[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# Run keychain, unless doing ssh auth forwarding
if [ "x$SSH_AUTH_FORWARD" = "x" ]; then
    # Configure
    keychain_options="--agents ssh --ignore-missing -q"
    keychain_keys="identity id_rsa id_dsa 74E31689"

    # Load keychain
    which keychain >/dev/null 2>&1 \
        && keychain $keychain_options $keychain_keys
    for file in "$HOME/.keychain/${HOSTNAME}-sh"*; do
        [ -f "$file" ] && source "$file"
    done
fi

# Ensure last comand run on login is success
true
