#! /bin/bash

# Add a few additional path entries
add_path() {
    if [ "x$PATH" = "x" ]; then
        export PATH="$1"
    elif ! echo "$PATH" | tr ':' '\n' | grep -Fxq "$1"; then
        export PATH="$1:$PATH"
    fi
}
add_path "/sbin"
add_path "/usr/sbin"
add_path "/usr/local/sbin"
for path in ~/.gem/*/*/bin /opt/*/bin /opt/*/*/bin; do
    [ -d "$path" ] && add_path "$path"
done
add_path "$HOME/bin"

# If not running interactively, don't do anything else
case $- in
    *i*) ;;
      *) return ;;
esac

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it
shopt -s histappend

# For setting history length see HISTSIZE and HISTFILESIZE
HISTSIZE=10000
HISTFILESIZE=200000

# Check the window size after each command and, if necessary, update
# the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar >/dev/null 2>&1

# Pull in external definitions when available
source_exists() {
  [[ -f "$1" ]] && source "$1"
}
source_exists /etc/bash_completion
source_exists /usr/share/autojump/autojump.sh

# Convenient when navigating around files and directories
ls_or_cmd() {
    local cmd=$1; shift
    if [[ -d "$1" ]]; then
        ls "$@"
    else
        "$cmd" "$@"
    fi
}
alias cat='ls_or_cmd cat'
alias less='ls_or_cmd less'

# Pager options etc
export PAGER=less
alias les='less'
export LESS="-R -i -X"
[ -x /usr/bin/lesspipe ] \
    && eval "$(SHELL=/bin/sh lesspipe)"

# Options for ls
case $(uname) in
    Linux)  alias ls='ls --color=auto --ignore-backups -I "#*"' ;;
    Darwin) alias ls='ls -G' ;;
esac
alias h='ls'
alias hh='ls -l'

# Options for grep
alias grep='grep --color=auto'

# Utility functions
quiet() {
    "$@" >/dev/null 2>&1
}

nhq() {
    eval "nohup $@ >/dev/null 2>&1 </dev/null &"
}
nhl() {
    eval "nohup $@ >${1}.log 2>&1 </dev/null &"
}
nha() {
    eval "nohup $@ >>${1}.log 2>&1 </dev/null &"
}

hc() {
    [[ $# == 0 ]] \
        && unset HADOOP_CONF_DIR \
        || export HADOOP_CONF_DIR=/etc/hadoop/conf.$1
}

dirty-files() {
    (
        git ls-files -o -X .gitignore
        git ls-files -o --directory
    ) | sort | uniq -u
}

# Editor definition
if quiet which emacsclient && quiet emacsclient -e '1'; then
    export EDITOR='emacsclient'
    alias vi='emacsclient -n'
else
    export EDITOR='nano -w'
    alias vi='nano -w'
fi
alias nano='nano -w'

# Browser (if used?)
export BROWSER=conkeror

# Sorting
export LC_COLLATE=C

# Randomness
alias comitor="~/ws/comitor/comitor.rb > ~/tmp/comics.html \
                 && conkeror ~/tmp/comics.html"


# Prompt
__my_git_ps1() {
    __git_ps1 2>/dev/null | sed -r -e 's, *\((.*)\),\1,'
}

__git_status() {
    local status
    if quiet git status --porcelain; then
        status=" git:"
        if git status --porcelain | grep -Eq '^( M|\?\?)'; then
            status="${status}\033[31m"
        elif git status --porcelain | grep -Eq '^(M |A )'; then
            status="${status}\033[32m"
        else
            status="${status}\033[35m"
        fi
        status="${status}$(__my_git_ps1)\033[0m"
    fi
    echo "$status"
}

__ruby_status() {
    local status
    if [[ "x$GEM_HOME" != "x" ]]; then
        status=$(basename "$GEM_HOME")
        if [[ "$status" == .* ]]; then
            status=$(basename "$(dirname "$GEM_HOME")")
        fi
        status=" rb:\033[36m${status}\033[0m"
    fi
    echo "$status"
}

__python_status() {
    local status
    if [[ "x$VIRTUAL_ENV" != "x" ]]; then
        status=$(basename "$VIRTUAL_ENV")
        if [[ "$status" == .* ]]; then
            status=$(basename "$(dirname "$VIRTUAL_ENV")")
        fi
        status=" py:\033[36m${status}\033[0m"
    fi
    echo "$status"
}

__schroot_status() {
    local status
    if [[ "x$SCHROOT_CHROOT_NAME" != "x" ]]; then
        status=" schroot:\033[36m${SCHROOT_CHROOT_NAME}\033[0m"
    fi
    echo "$status"
}

__hadoop_status() {
    local status
    if [[ "x$HADOOP_CONF_DIR" != "x" ]]; then
        status=$(basename "$HADOOP_CONF_DIR")
        status=" hadoop:\033[36m${status:5}\033[0m"
    fi
    echo "$status"
}

prompt_command() {
    EXITSTATUS=$?

    local exit_status
    [[ $EXITSTATUS = 0 ]] \
        && exit_status="\033[32m$EXITSTATUS\033[0m" \
        || exit_status="\033[31m$EXITSTATUS\033[0m"

    PS1="\n"
    [[ "x$TERM" = "xscreen" ]] \
        && PS1="${PS1}\033k\033\134@\\h\n\033[1A"
    PS1="${PS1}∴ ${exit_status} \\h:\033[34m\\w\033[0m"
    PS1="${PS1}$(__git_status)"
    PS1="${PS1}$(__schroot_status)"
    PS1="${PS1}$(__ruby_status)"
    PS1="${PS1}$(__python_status)"
    PS1="${PS1}$(__hadoop_status)"
    PS1="${PS1}\n\\$ "

    export PS1
}
export PROMPT_COMMAND="prompt_command ; $AUTOJUMP"
