#! /bin/bash

# This file is sourced by bash when you log in interactively.

# Load general bash configuration
[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# Run keychain, unless doing ssh auth forwarding
if [[ -z $SSH_AUTH_FORWARD ]]; then
    # Configure
    keychain_options="--agents ssh,gpg --ignore-missing -q --inherit any"
    keychain_keys="id_rsa llasram@cybraics.rsa 74E31689"

    # Load keychain
    which keychain >/dev/null 2>&1 \
        && keychain $keychain_options $keychain_keys
    for file in "$HOME/.keychain/${HOSTNAME}-sh"*; do
        [ -f "$file" ] && source "$file"
    done
fi

# Ensure last comand run on login is success
true
