#! /bin/bash

# Add a few additional path entries
add_path() {
    if [ "x$PATH" = "x" ]; then
        export PATH="$1"
    elif ! echo "$PATH" | tr ':' '\n' | grep -Fxq "$1"; then
        export PATH="$1:$PATH"
    fi
}
for path in /opt/*/bin /opt/*/*/bin; do
    [ -d "$path" ] && add_path "$path"
done
add_path "$HOME/bin"

# If not running interactively, don't do anything else
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it
shopt -s histappend

# For setting history length see HISTSIZE and HISTFILESIZE
HISTSIZE=10000
HISTFILESIZE=200000

# Check the window size after each command and, if necessary, update
# the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# Pull in external definitions when available
source_exists() {
  [[ -f "$1" ]] && source "$1"
}
source_exists /etc/bash_completion
source_exists /usr/share/autojump/autojump.sh

# Convenient when navigating around files and directories
ls_or_cmd() {
    local cmd=$1; shift
    if [[ -d "$1" ]]; then
        ls "$@"
    else
        "$cmd" "$@"
    fi
}
alias cat='ls_or_cmd cat'
alias less='ls_or_cmd less'

# Pager options etc
export PAGER=less
alias les='less'
export LESS="-R -i -X"
[ -x /usr/bin/lesspipe ] \
    && eval "$(SHELL=/bin/sh lesspipe)"

# Options for ls
alias ls='ls --color=auto --ignore-backups -I "#*"'
alias h='ls'
alias hh='ls -l'

# Options for grep
alias grep='grep --color=auto'

# Utility functions
quiet() {
    "$@" >/dev/null 2>&1
}

# Editor definition
if quiet which emacsclient && quiet emacsclient -e '1'; then
    export EDITOR='emacsclient'
    alias vi='emacsclient -n'
else
    export EDITOR='nano -w'
    alias vi='nano -w'
fi
alias nano='nano -w'

# Browser (if used?)
export BROWSER=conkeror

# Sorting
export LC_COLLATE=C

# Randomness
alias comitor="~/ws/comitor/comitor.rb > ~/tmp/comics.html \
                 && conkeror ~/tmp/comics.html"

# Prompt
prompt_command() {
    EXITSTATUS=$?

    local exit_status
    local git_status

    [[ $EXITSTATUS = 0 ]] \
        && exit_status="\033[32m$EXITSTATUS\033[0m" \
        || exit_status="\033[31m$EXITSTATUS\033[0m"

    if ! quiet git status --porcelain; then
        git_status="        "
    elif git status --porcelain | grep -Eq '^( M|\?\?)'; then
        git_status="\033[31m"
    elif git status --porcelain | grep -Eq '^(M |A )'; then
        git_status="\033[32m"
    else
        git_status="\033[35m"
    fi
    git_status="${git_status}$(__git_ps1 2>/dev/null)\033[0m"

    PS1="\n\033k\033\134@\\h\n\033[1A"
    PS1="${PS1}∴ ${exit_status} \\h:\033[34m\\w\033[0m${git_status}\n"
    PS1="${PS1}\\$ "

    export PS1
}
export PROMPT_COMMAND="prompt_command ; $AUTOJUMP"
