#! /bin/bash

# Utility functions

# unaliased 'which'
GOOD_WHICH="$HOME/export/$CONFIG_GUESS/bin/which"
[ -x "$GOOD_WHICH" ] || GOOD_WHICH="which"
GOOD_WHICH_ARGS=''
for ARG in --skip-alias --skip-functions; do
    if ! echo '' \
		| $GOOD_WHICH $ARG which 2>&1 \
		| grep -- "$ARG" >/dev/null 2>&1 \
	&& echo '' \
		| $GOOD_WHICH $ARG which 2>&1 \
		| grep 'which$' >/dev/null 2>&1;
    then
	GOOD_WHICH_ARGS="$GOOD_WHICH_ARGS $ARG" ;
    fi ;
done
good_which() {
    $GOOD_WHICH ${GOOD_WHICH_ARGS} "${@}"
}
alias gwhich='good_which'
alias rwhich="$GOOD_WHICH"

# Absolute path of a directory
abs_dir() {
    local wd="$PWD"
    
    builtin cd "$1" 2>/dev/null
    dir="$PWD"
    builtin cd "$wd" 2>/dev/null

    echo "$dir"
}

# Find the absolute path of a file
abs_file() {
    echo "$(abs_dir "$(dirname "$1")")/$(basename "$1")"
}

# 'which' based on return-value
retval_which() {
    local retval=1

    if good_which "${1}" 2>&1 | grep "${1}\$" >/dev/null 2>&1; then
	retval=0 ;
    fi

    return ${retval} ;
}

# Add paths to a variable or initialize if empty
function add_path () {
    [ "${1}" ] || return 1

    if eval "test \$${1}"; then
	eval "${1}=\"\$${1}:${2}\"" ;
    else
	eval "${1}=\"${2}\"" ;
    fi
}

# Use 'head' to see only N lines
HEADN_ARG='-n '
if ! ( echo 'foo' | head -n 1 2>&1 | 
	grep 'foo' >/dev/null 2>&1 ); then
    HEADN_ARG='-'
fi
headn() {
    eval "head ${HEADN_ARG}$@"
}

# Do simple quoting of arguments for passing to 'eval'
squote() {
    args=''
    while [ $# != 0 ]; do
	args="$args '$1'";
	shift
    done
    echo "$args"
}

# Fetch <username>:<password> from authinfo
authinfo() {
    cat "$AUTHINFO" \
        | fgrep "machine $1 " \
        | grep -o '\(login\|password\) [^ ]*' \
        | cut -d' ' -f2 \
        | paste -sd:
}
