#! /bin/bash

# Pager which lists directories
pager_fn() {
    if [ -d "$1" ]; then
        eval "ls $@"
    else
        ${PAGER} "$@" ;
    fi
}
alias less='pager_fn'
alias more='pager_fn'
alias les='pager_fn'

# A 'cat' which lists directories
cat_fn() {
    if [ -d "$1" ]; then
        eval "ls $@"
    else
        env cat "$@" ;
    fi
}
alias cat='cat_fn'

# The most powerful 'which' available
my_which_args=''
for ARG in --tty-only --read-alias --read-functions --show-tilde --show-dot; do
    if ! echo '' | which $ARG which 2>&1 | grep -- "$ARG" >/dev/null 2>&1 \
        && echo '' | which $ARG which 2>&1 | grep 'which$' >/dev/null 2>&1; then
        my_which_args="$my_which_args $ARG" ;
    fi ;
done
which_fn() {
    (alias; declare -f) | env which $my_which_args $@
}
alias which='which_fn'

# Silly, but *necessary* (seriously)
nice_fn () {
    if [ "x$@" = "x" ]; then
        echo 0 ;
    else
        nice $@ ;
    fi
}       
nice >/dev/null 2>&1 \
    || alias nice='nice_fn'

# GNU 'who' acts oddly sometimes...
[ "x$(who)" = "x" ] \
    && alias who='who /var/run/utmp'

# Pull in preferred color scheme
retval_which dircolors \
    && [ -f "$HOME/.dir_colors" ] \
    && eval "$(dircolors -b $HOME/.dir_colors)"

# Most useful 'ls' available
ls_args="--color=auto"
ls_args="$ls_args --ignore-backups -I 'System Volume Information'"
ls_args="$ls_args -I '#*'"
alias ls="ls $ls_args"
ls >/dev/null 2>&1 || alias ls='ls --color'
ls >/dev/null 2>&1 || alias ls='ls -F'
ls >/dev/null 2>&1 || unalias ls
alias rls='env ls'

# Short dvorak-happy aliases
alias h='ls'
alias hh='ls -l'
alias rh='rls'

# Portage ls
pls() {
    eval "ls -d /usr/portage/*/*'$1'*"
}

# Most useful 'grep' available
export GREP_COLOR="0;34"
alias grep='grep --color=auto'
echo 'test' | grep 'test' >/dev/null 2>&1 || unalias grep
alias rgrep='env grep'

# ps + grep = profit
pg_fn() {
    pattern="$(echo "$1" | sed -e's,^\(.\),[\1],')"
    ps aux | grep "$pattern"
}
alias pg='pg_fn'

# Editor aliases
if retval_which gnuclient; then
    EDITOR="gnuclient"
    alias vi='gnuclient -q'
elif retval_which emacsclient; then
    EDITOR="emacsclient"
    alias vi='emacsclient -n'
elif retval_which nano; then
    EDITOR="nano -w"
    alias vi='nano -w'
elif retval_which vim; then
    EDITOR="vim -X"
    alias vi='vim -X'
else
    EDITOR="vi"
fi
export EDITOR

if ! retval_which vim && retval_which vi; then
    alias vim="$(good_which vi)"
else
    alias vim="vim -X"
fi
alias nano='nano -w'

# hexl-find-file from the terminal
hvi() {
    gnuclient -batch -eval "(hexl-find-file \"$(abs_file "$1")\")"
}

# Make a new emacs frame on this display
emacs-here() {
    gnuclient -batch -eval "(make-frame-on-display \"$DISPLAY\")"
}

# Like 'wget', but with 'curl'
cget_fn() {
    curl -L -g -n -C - -o "$(basename "$1" | sed -e's,[?].*,,')" "$1"
}
alias cget='cget_fn'

# Smarter 'find'
export SFIND_PRUNE_PATS='*~:*/CVS:*/.svn'
sfind() {
    local dirs=''
    while [ $# != 0 ]; do
        echo "$1" | grep '^-' >/dev/null 2>&1 && break
        dirs="$dirs '$1'"; shift
    done
    local opts="$(squote "$@")"

    local prune_args="-path '$(\
        echo "$SFIND_PRUNE_PATS" | sed -e "s,:,' -o -path ',g")'"
    eval "find $dirs \
              '(' '(' $prune_args ')' -prune ')' \
              -o $opts -print"
}

# Smarter 'pushd'
pushd_fn() {
    case "$1" in
        (+*) builtin pushd "$@" ;;
        ('') builtin pushd ;;
    esac
    [ -d "$1" ] || return 1

    local dir="$(abs_dir "$1")"
    if builtin dirs -l -v | grep " $dir\$" >/dev/null 2>&1; then
        n="$(dirs -v -l | grep " $dir\$" | awk '{ print $1 }')"
        builtin popd +"$n" >/dev/null 2>&1
        builtin pushd "$dir"
    else
        builtin pushd "$1"
    fi
}
alias pushd='pushd_fn'

# Directory changing should be stateful
alias cd='pushd_fn'
alias rcd='builtin cd'
function cdb() { builtin pushd; }
alias pd='popd'
alias ch='cd'
alias dirs='dirs -v'

# Source .bashrc changes
alias sb='source ~/.bashrc'

# ifconfig <=> ipconfig
retval_which ifconfig || alias ifconfig='ipconfig'
retval_which ipconfig || alias ipconfig='ifconfig'

# hd => hexdump/od
if retval_which hexdump; then
    alias hd='hexdump -C'
elif retval_which od; then
    alias hd='od -t x4z'
fi

# jing, if present
if [ -f "$HOME/src/jing-20030619/bin/jing.jar" ]; then
    alias jing="java -jar $HOME/src/jing-20030619/bin/jing.jar"
fi

# Comitor smash!
alias comitor="~/ws/comitor/comitor.rb > ~/tmp/comics.html \
                 && conkeror ~/tmp/comics.html"

# Epubcheck, oh how we love thee
if [ -f "$HOME/src/epubcheck/epubcheck.jar" ]; then
    alias epubcheck="java -jar $HOME/src/epubcheck/epubcheck.jar"
fi
