#! /bin/bash

# This file is all about the prompt command
PROMPT_COMMAND=prompt_command

# Shell options we have loved...
eval "shopt -u promptvars" >/dev/null 2>&1

# Number of lines in history stack
histnum='1'

# Probably only need to figure these out once per login...
uname_r="$(uname -r)"
is_ssh="$([ "x$SSH_CLIENT" != "x" ] && echo '=[ssh]')"

# Initial null vars
unset NOTE TITLE UPDATE

# The prompt command itself
prompt_command() {
	# fix for bash history
	history -a
	history="$(history $histnum | cut -b'8-' | sed -e's,\\,\\\\,g')"
    note="${NOTE:+=[NOTE=$NOTE]}"
    update="${UPDATE:+=[[5;1;31m$UPDATE[0m]}"

    # 'screen' title escape
	PS1="\033k\033\134@${TITLE:+$TITLE:}\h\n\033[1A"

    # The real prompt
	PS1="$PS1[\u@\h]=[$CONFIG_GUESS @${uname_r}]${is_ssh}=[$TERM]\n"
	PS1="$PS1[\d \t]=[$history]\n"
	PS1="$PS1[\#]=[\w]$update$note\n"
	PS1="$PS1\\$ "
	
	export PS1
}

note() {
	if [ "x$*" = "x" ]; then
		unset NOTE
	else
		NOTE="$*"
	fi
}

title () {
	if [ "x$*" = "x" ]; then
		unset TITLE
	else
        saved_IFS="$IFS"; IFS="-"
		TITLE="$*"
        IFS="$saved_IFS"
	fi
}
