;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-skip-close-maybe
        beginning-of-buffer
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        c-indent-new-comment-line
        dabbrev-expand
        downcase-region
        downcase-region
        electric-pair-delete-pair
        ensime-company-complete-or-indent
        ess-smart-comma
        forward-sexp
        generic-hungry-backspace
        generic-hungry-delete
        indent-for-tab-command
        kill-region
        mark-sexp
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        org-yank
        paredit-doublequote
        paredit-forward-slurp-sexp
        search-forward
        ))

(setq mc/cmds-to-run-once
      '(
        handle-switch-frame
        org-cycle
        yank-rectangle
        ))
