;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-skip-close-maybe
        beginning-of-buffer
        c-electric-paren
        c-electric-semi&comma
        c-indent-line-or-region
        c-indent-new-comment-line
        downcase-region
        ess-smart-comma
        generic-hungry-backspace
        generic-hungry-delete
        kill-region
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        org-yank
        ))

(setq mc/cmds-to-run-once
      '(
        handle-switch-frame
        yank-rectangle
        ))
