;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-skip-close-maybe
        beginning-of-buffer
        downcase-region
        generic-hungry-backspace
        generic-hungry-delete
        kill-region
        ))

(setq mc/cmds-to-run-once
      '(
        handle-switch-frame
        yank-rectangle
        ))
